# Generated by Django 5.2.3 on 2025-06-20 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalreport',
            old_name='ai_summary',
            new_name='ai_prompt_preview',
        ),
    ]
