# Generated by Django 5.2.3 on 2025-06-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_ai_summary_medicalreport_ai_prompt_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
