# Generated by Django 5.2.1 on 2025-06-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_medicalreport_ai_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='report_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
